-- 코드를 입력하세요
SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME, SUM(PRO.PRICE *ORD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT PRO
JOIN FOOD_ORDER ORD ON PRO.PRODUCT_ID = ORD.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRO.PRODUCT_ID ASC